=== nextflow-io/schema-builder/tests/meta_nextflow_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://nextflow.io",
    "title": "Nextflow Schema Meta-schema",
    "description": "Meta-schema to validate Nextflow parameter schema files",
    "type": "object",
    "properties": {
        "$schema": {
            "title": "schema",
            "type": "string",
            "minLength": 1
        },
        "$id": {
            "title": "ID URI",
            "type": "string",
            "minLength": 1
        },
        "title": {
            "title": "Title",
            "type": "string",
            "minLength": 1
        },
        "description": {
            "title": "Description",
            "type": "string",
            "minLength": 1
        },
        "type": {
            "title": "Top level type",
            "type": "string",
            "const": "object"
        },
        "$defs": {
            "title": "Parameter groups",
            "type": "object",
            "patternProperties": {
                "^.*$": {
                    "type": "object",
                    "required": [
                        "title",
                        "type",
                        "properties"
                    ],
                    "properties": {
                        "title": {
                            "type": "string",
                            "minLength": 1
                        },
                        "type": {
                            "const": "object"
                        },
                        "fa_icon": {
                            "type": "string",
                            "pattern": "^fa"
                        },
                        "description": {
                            "type": "string"
                        },
                        "required": {
                            "type": "array"
                        },
                        "properties": {
                            "$ref": "#/$defs/parameterOptions"
                        },
                        "dependentRequired": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                },
                                "uniqueItems": true,
                                "default": []
                            }
                        }
                    }
                }
            }
        },
        "properties": {
            "$ref": "#/$defs/parameterOptions"
        },
        "dependentRequired": {
            "type": "object",
            "additionalProperties": {
                "type": "array",
                "items": {
                    "type": "string"
                },
                "uniqueItems": true,
                "default": []
            }
        },
        "allOf": {
            "title": "Combine definition groups",
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "$ref"
                ],
                "properties": {
                    "$ref": {
                        "type": "string",
                        "pattern": "^#/\\$defs/[^/]+$"
                    }
                }
            }
        }
    },
    "required": [
        "$schema",
        "$id",
        "title",
        "description",
        "type"
    ],
    "$defs": {
        "typeAnnotation": {
            "type": "string",
            "enum": [
                "string",
                "boolean",
                "integer",
                "number",
                "null"
            ]
        },
        "allTypes": {
            "type": [
                "integer",
                "boolean",
                "number",
                "string",
                "null"
            ]
        },
        "nonNegativeInteger": {
            "type": "integer",
            "minimum": 0
        },
        "parameterOptions": {
            "type": "object",
            "patternProperties": {
                "^.*$": {
                    "type": "object",
                    "required": [
                        "type"
                    ],
                    "dependentSchemas": {
                        "exists": {
                            "$comment": "This checks if the type is a 'string' and the format corresponds to a file or directory when 'exists' is used.",
                            "properties": {
                                "type": {
                                    "const": "string"
                                },
                                "format": {
                                    "enum": [
                                        "path",
                                        "file-path",
                                        "file-path-pattern",
                                        "directory-path"
                                    ]
                                }
                            }
                        },
                        "schema": {
                            "$comment": "This checks if the type is a 'string' and the format is 'path' or 'file-path'",
                            "properties": {
                                "type": {
                                    "const": "string"
                                },
                                "format": {
                                    "enum": [
                                        "path",
                                        "file-path"
                                    ]
                                }
                            }
                        }
                    },
                    "properties": {
                        "type": {
                            "description": "The type of the parameter value. Can be one or more of these: `['integer', 'boolean', 'number', 'string', 'null']`",
                            "anyOf": [
                                {
                                    "$ref": "#/$defs/typeAnnotation"
                                },
                                {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/$defs/typeAnnotation"
                                    }
                                }
                            ]
                        },
                        "format": {
                            "type": "string",
                            "description": "The format of a parameter value with the 'string' type. This is used for additional validation on the structure of the value.",
                            "enum": [
                                "file-path",
                                "directory-path",
                                "path",
                                "file-path-pattern",
                                "date-time",
                                "date",
                                "time",
                                "email",
                                "uri",
                                "regex"
                            ]
                        },
                        "exists": {
                            "type": "boolean",
                            "description": "NON STANDARD OPTION: Check if a file exists. This parameter value needs to be a 'string' type with one of these formats: ['path', 'file-path', 'directory-path', 'file-path-pattern']"
                        },
                        "pattern": {
                            "type": "string",
                            "format": "regex",
                            "minLength": 1,
                            "description": "Check a parameter value of 'string' type against a regex pattern"
                        },
                        "schema": {
                            "type": "string",
                            "minLength": 1,
                            "pattern": "\\.json$",
                            "description": "NON STANDARD OPTION: Check the given file against a schema passed to this keyword. Will only work when type is 'string' and format is 'path' or 'file-path'"
                        },
                        "description": {
                            "type": "string",
                            "description": "NON STANDARD OPTION: The description of the currrent parameter"
                        },
                        "help_text": {
                            "type": "string",
                            "description": "NON STANDARD OPTION: A more detailed help text"
                        },
                        "fa_icon": {
                            "type": "string",
                            "pattern": "^fa",
                            "description": "NON STANDARD OPTION: A font awesome icon to use in the nf-core parameter documentation"
                        },
                        "errorMessage": {
                            "type": "string",
                            "minLength": 1,
                            "description": "NON STANDARD OPTION: The custom error message to display in case validation against this parameter fails. Can also be used as a deprecation message if 'deprecated' is true"
                        },
                        "default": {
                            "$ref": "#/$defs/allTypes",
                            "description": "Specifies a default value to use for this parameter"
                        },
                        "examples": {
                            "type": "array",
                            "items": {
                                "$ref": "#/$defs/allTypes"
                            },
                            "description": "A list of examples for the current parameter"
                        },
                        "deprecated": {
                            "type": "boolean",
                            "description": "States that the parameter is deprecated. Please provide a nice deprecation message using 'errorMessage'"
                        },
                        "hidden": {
                            "type": "boolean",
                            "description": "NON STANDARD OPTION: Hide this parameter from the help message and documentation"
                        },
                        "minLength": {
                            "$ref": "#/$defs/nonNegativeInteger",
                            "description": "The minimum length a 'string' parameter value should be"
                        },
                        "maxLength": {
                            "$ref": "#/$defs/nonNegativeInteger",
                            "description": "The maximum length a 'string' parameter value should be"
                        },
                        "minimum": {
                            "type": "number",
                            "description": "The mimimum value an 'integer' or 'number' parameter value should be"
                        },
                        "exclusiveMinimum": {
                            "type": "number",
                            "description": "The exclusive mimimum value an 'integer' or 'number' parameter value should be"
                        },
                        "maximum": {
                            "type": "number",
                            "description": "The maximum value an 'integer' or 'number' parameter value should be"
                        },
                        "exclusiveMaximum": {
                            "type": "number",
                            "description": "The exclusive maximum value an 'integer' or 'number' parameter value should be"
                        },
                        "multipleOf": {
                            "type": "number",
                            "description": "The 'integer' or 'number' parameter value should be a multiple of this value"
                        },
                        "enum": {
                            "type": "array",
                            "uniqueItems": true,
                            "items": {
                                "$ref": "#/$defs/allTypes"
                            },
                            "description": "The parameter value should be one of the values specified in this enum array"
                        },
                        "const": {
                            "$ref": "#/$defs/allTypes",
                            "description": "The parameter value should be equal to this value"
                        }
                    }
                }
            }
        }
    }
}

=== nextflow-io/schema-builder/tests/test-schema-full.json
{
  "$defs": {
    "input_output": {
      "title": "Input/output",
      "type": "object",
      "fa_icon": "fas fa-terminal",
      "description": "Define where the pipeline should find input data and save output data.",
      "required": [
        "input",
        "outdir"
      ],
      "properties": {
        "input": {
          "type": "string",
          "format": "file-path",
          "exists": true,
          "schema": "assets/schema_input.json",
          "mimetype": "text/csv",
          "pattern": "^\\S+\\.csv$",
          "description": "Path to comma-separated file containing information about the samples in the experiment.",
          "help_text": "You will need to create a design file with information about the samples in your experiment before running the pipeline. Use this parameter to specify its location. It has to be a comma-separated file with 3 columns, and a header row. See [usage docs](https://nf-co.re/rnaseq/usage#samplesheet-input).",
          "fa_icon": "fas fa-7",
          "default": ""
        },
        "outdir": {
          "type": "string",
          "format": "directory-path",
          "description": "The output directory where the results will be saved. You have to use absolute paths to storage on Cloud infrastructure.",
          "fa_icon": "fas fa-folder-open"
        },
        "email": {
          "type": "string",
          "description": "Email address for completion summary.",
          "fa_icon": "fas fa-envelope",
          "help_text": "Set this parameter to your e-mail address to get a summary e-mail with details of the run sent to you when the workflow exits. If set in your user config file (`~/.nextflow/config`) then you don't need to specify this on the command line for every run.",
          "pattern": "^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$"
        },
        "multiqc_title": {
          "type": "string",
          "description": "MultiQC report title. Printed as page header, used for filename if not otherwise specified.",
          "fa_icon": "fas fa-file-signature"
        }
      }
    },
    "reference_genome_options": {
      "title": "Reference genome options",
      "type": "object",
      "fa_icon": "fas fa-dna",
      "description": "Reference genome related files and options required for the workflow.",
      "properties": {
        "genome": {
          "type": "string",
          "description": "Name of iGenomes reference.",
          "fa_icon": "fas fa-book",
          "help_text": "If using a reference genome configured in the pipeline using iGenomes, use this parameter to give the ID for the reference. This is then used to build the full paths for all required reference genome files e.g. `--genome GRCh38`. \n\nSee the [nf-core website docs](https://nf-co.re/usage/reference_genomes) for more details."
        },
        "fasta": {
          "type": "string",
          "format": "file-path",
          "exists": true,
          "mimetype": "text/plain",
          "pattern": "^\\S+\\.fn?a(sta)?(\\.gz)?$",
          "description": "Path to FASTA genome file.",
          "help_text": "This parameter is *mandatory* if `--genome` is not specified. If you don't have a BWA index available this will be generated for you automatically. Combine with `--save_reference` to save BWA index for future runs.",
          "fa_icon": "far fa-file-code"
        },
        "igenomes_ignore": {
          "type": "boolean",
          "description": "Do not load the iGenomes reference config.",
          "fa_icon": "fas fa-ban",
          "hidden": true,
          "help_text": "Do not load `igenomes.config` when running the pipeline. You may choose this option if you observe clashes between custom parameters and those supplied in `igenomes.config`."
        },
        "igenomes_base": {
          "type": "string",
          "format": "directory-path",
          "description": "The base path to the igenomes reference files",
          "fa_icon": "fas fa-ban",
          "hidden": true,
          "default": "s3://ngi-igenomes/igenomes/"
        }
      }
    },
    "institutional_config_options": {
      "title": "Institutional config options",
      "type": "object",
      "fa_icon": "fas fa-university",
      "description": "Parameters used to describe centralised config profiles. These should not be edited.",
      "help_text": "The centralised nf-core configuration profiles use a handful of pipeline parameters to describe themselves. This information is then printed to the Nextflow log when you run a pipeline. You should not need to change these values when you run a pipeline.",
      "properties": {
        "custom_config_version": {
          "type": "string",
          "description": "Git commit id for Institutional configs.",
          "default": "master",
          "hidden": true,
          "fa_icon": "fas fa-users-cog"
        },
        "custom_config_base": {
          "type": "string",
          "description": "Base directory for Institutional configs.",
          "default": "https://raw.githubusercontent.com/nf-core/configs/master",
          "hidden": true,
          "help_text": "If you're running offline, Nextflow will not be able to fetch the institutional config files from the internet. If you don't need them, then this is not a problem. If you do need them, you should download the files from the repo and tell Nextflow where to find them with this parameter.",
          "fa_icon": "fas fa-users-cog"
        },
        "config_profile_name": {
          "type": "string",
          "description": "Institutional config name.",
          "hidden": true,
          "fa_icon": "fas fa-users-cog"
        },
        "config_profile_description": {
          "type": "string",
          "description": "Institutional config description.",
          "hidden": true,
          "fa_icon": "fas fa-users-cog"
        },
        "config_profile_contact": {
          "type": "string",
          "description": "Institutional config contact information.",
          "hidden": true,
          "fa_icon": "fas fa-users-cog"
        },
        "config_profile_url": {
          "type": "string",
          "description": "Institutional config URL link.",
          "hidden": true,
          "fa_icon": "fas fa-users-cog"
        }
      }
    },
    "generic_options": {
      "title": "Generic options",
      "type": "object",
      "fa_icon": "fas fa-file-import",
      "description": "Less common options for the pipeline, typically set in a config file.",
      "help_text": "These options are common to all nf-core pipelines and allow you to customise some of the core preferences for how the pipeline runs.\n\nTypically these options would be set in a Nextflow config file loaded for all pipeline runs, such as `~/.nextflow/config`.",
      "properties": {
        "version": {
          "type": "boolean",
          "description": "Display version and exit.",
          "fa_icon": "fas fa-question-circle",
          "hidden": true
        },
        "publish_dir_mode": {
          "type": "string",
          "default": "copy",
          "description": "Method used to save pipeline results to output directory.",
          "help_text": "The Nextflow `publishDir` option specifies which intermediate files should be saved to the output directory. This option tells the pipeline what method should be used to move these files. See [Nextflow docs](https://www.nextflow.io/docs/latest/process.html#publishdir) for details.",
          "fa_icon": "fas fa-copy",
          "enum": [
            "symlink",
            "rellink",
            "link",
            "copy",
            "copyNoFollow",
            "move"
          ],
          "hidden": true
        },
        "email_on_fail": {
          "type": "string",
          "description": "Email address for completion summary, only when pipeline fails.",
          "fa_icon": "fas fa-exclamation-triangle",
          "pattern": "^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$",
          "help_text": "An email address to send a summary email to when the pipeline is completed - ONLY sent if the pipeline does not exit successfully.",
          "hidden": true
        },
        "plaintext_email": {
          "type": "boolean",
          "description": "Send plain-text email instead of HTML.",
          "fa_icon": "fas fa-remove-format",
          "hidden": true
        },
        "max_multiqc_email_size": {
          "type": "string",
          "description": "File size limit when attaching MultiQC reports to summary emails.",
          "pattern": "^\\d+(\\.\\d+)?\\.?\\s*(K|M|G|T)?B$",
          "default": "25.MB",
          "fa_icon": "fas fa-file-upload",
          "hidden": true
        },
        "monochrome_logs": {
          "type": "boolean",
          "description": "Do not use coloured log outputs.",
          "fa_icon": "fas fa-palette",
          "hidden": true
        },
        "hook_url": {
          "type": "string",
          "description": "Incoming hook URL for messaging service",
          "fa_icon": "fas fa-people-group",
          "help_text": "Incoming hook URL for messaging service. Currently, MS Teams and Slack are supported.",
          "hidden": true
        },
        "multiqc_config": {
          "type": "string",
          "format": "file-path",
          "description": "Custom config file to supply to MultiQC.",
          "fa_icon": "fas fa-cog",
          "hidden": true
        },
        "multiqc_logo": {
          "type": "string",
          "description": "Custom logo file to supply to MultiQC. File name must also be set in the MultiQC config file",
          "fa_icon": "fas fa-image",
          "hidden": true
        },
        "multiqc_methods_description": {
          "type": "string",
          "description": "Custom MultiQC yaml file containing HTML including a methods description.",
          "fa_icon": "fas fa-cog"
        },
        "validate_params": {
